#pragma once

#include "KDE/ImguiManager.h"
#include "KDE/gl.h"
#include "Shader.h"
#include "VAO.h"
#include "VBO.h"
#include "EBO.h"
#include "Texture.h"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include "Camera.h"
#include "Mesh.h"
#include "KDE/Model.h"
#include "shapes/Cube.h"
#include "shapes/Plank.h"
#include "KDE/PointLight.h"
#include "Framebuffer.h"